# --- !Ups

CREATE TABLE `USER_PROFILE` (
  `USER_ID`      INT  NOT NULL REFERENCES `USER`(`USER_ID`),
  `PROVIDER_ID`  VARCHAR(255) NOT NULL,
  `PROVIDER_KEY` VARCHAR(255) NOT NULL,

  PRIMARY KEY (`PROVIDER_ID`, `PROVIDER_KEY`)
);

# --- !Downs

DROP TABLE `USER_PROFILE`;