# --- !Ups

CREATE TABLE `PASSWORD` (
  `PROVIDER_KEY` VARCHAR(254) NOT NULL PRIMARY KEY REFERENCES `USER_PROFILE`(`PROVIDER_KEY`),
  `HASHER`       TEXT         NOT NULL,
  `HASH`         TEXT         NOT NULL,
  `SALT`         TEXT
);

# --- !Downs
DROP TABLE `PASSWORD`;