CREATE TABLE `USER` (
  `USER_ID`      INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FIRST_NAME`   TEXT,
  `LAST_NAME`    TEXT,
  `EMAIL`        TEXT,
  `PROVIDER_ID`  TEXT NOT NULL,
  `PROVIDER_KEY` TEXT NOT NULL
);

CREATE TABLE `USER_PROFILE` (
  `USER_ID`      INT  NOT NULL REFERENCES `USER`(`USER_ID`),
  `PROVIDER_ID`  TEXT NOT NULL,
  `PROVIDER_KEY` TEXT NOT NULL,

  PRIMARY KEY (`PROVIDER_ID`, `PROVIDER_KEY`)
);

CREATE TABLE `PASSWORD` (
  `AUTH_KEY` VARCHAR(254) NOT NULL PRIMARY KEY,
  `HASHER`   TEXT         NOT NULL,
  `HASH`     TEXT         NOT NULL,
  `SALT`     TEXT
);